- name: Check if Kubernetes is installed
  stat:
    path: /etc/kubernetes/admin.conf
  register: kubernetes_installed
  
- name: Install Packages
  package:
    name: "{{item}}"
    state: present
  with_items: "{{packages}}"

- name: Add Docker apt key
  apt_key:
    url: "{{ docker_repo_url }}"
    id: "{{ docker_repo_apt_id }}"
    state: present
  register: add_repository_key
  ignore_errors: true

- name: Add Docker repository
  apt_repository:
    repo: "{{ docker_apt_repository }}"
    state: present
    update_cache: yes

- name: Install Docker
  apt:
    name: "{{ docker_package }}"
    state: present
  environment:
    # Prevent service from starting
    RUNLEVEL: 1

- name: Enable Docker
  systemd:
    name: docker
    state: started
    daemon_reload: yes
    enabled: yes

- name: Add Kubernetes apt key
  apt_key:
    url: "{{ kubernetes_apt_key }}"
    state: present

- name: Add Kubernetes repository
  apt_repository:
    repo: "{{ kubernetes_repo }}"
    state: present
    update_cache: true

- name: Update apt packages
  apt:
    update_cache: yes
  when: not kubernetes_installed.stat.exists

- name: Install Kube packages
  package:
    name: "{{item}}"
    state: present
  with_items: "{{kube_packages}}"
  notify: restart kubelet

- name: Remove swapfile from /etc/fstab
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- meta: flush_handlers